site_name: Digital Capability Locator

repo_url: https://github.com/Digital-Business-Council/Digital-Capability-Locator

pages:

    - 'Disclaimer & Audience': 'Index.md'

    - 'Introduction': 'Introduction.md'

    - 'Epic Overview': 'Epics.md'

    - 'Epic 001': 'Epic001.md'
