site_name: Digital Capability Locator
repo_url: https://github.com/Digital-Business-Council/Digital-Capability-Locator
pages:
    - 'Disclaimer & Audience': 'index.md'
    - Business Requirements:
        - 'Introduction': 'Introduction.md'
        - Epics:
            - 'Overview of Epics': 'Epics.md'
            - 'Epic 001': 'Epic001.md' 
            - 'Epic 002': 'Epic002.md'
    - Quality of Service Requirements:
        - 'Introduction': 'Quality of Service Requirements/Introduction.md'
    - Architecture:
        - 'Arch 1': 'Architecture/Introduction.md'
    - 'API Definitions': 'API Definitions/Introduction.md'
    - 'API Test Assertions': 'API Test Assertions/Introduction.md'
theme: mkdocs
