site_name: Digital Capability Locator
repo_url: https://github.com/Digital-Business-Council/Digital-Capability-Locator
pages:
    - 'Disclaimer & Audience': 'index.md'
    - Requirements:
        - 'Introduction': 'Introduction.md'
        - Epics:
            - 'Overview of Epics': 'Epics.md'
            - 'Epic 001': 'Epic001.md' 
    - Architecture:
        - 'Arch 1' : 'index.md'
    - 'API Defintions' : 'index.md'
    - 'Test Assertions' : 'index.md'
theme: mkdocs
